name: CI

on:
  - pull_request
  - push
  - workflow_dispatch

jobs:
  test:
    name: Test on Node.js ${{ matrix.node-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 17
          - 16
          - 14
          - 12

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache pnpm store
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key:
            ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - run: npm install -g pnpm

      - run: pnpm install

      - run: pnpm run build

      - run: pnpm test

      - run: pnpm store prune

# vim: et sts=2 sw=2
